version: '3.8'

networks:
  frontend:
  backend:

services:
  haproxy:
    build: ./docker/haproxy
    ports:
      - "80:80"
      - "8404:8404"
    networks:
      - frontend
    depends_on:
      - app1
      - app2

  app1:
    build: ./docker/app
    networks:
      - frontend
      - backend
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  app2:
    build: ./docker/app
    networks:
      - frontend
      - backend
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    build: ./docker/redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data

volumes:
  redis_data: