version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: publicnotes-app1
    networks:
      - backend

  app2:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: publicnotes-app2
    networks:
      - backend

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - backend

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
      - "8404:8404" 
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend

networks:
  backend: