version: '3.8'

networks:
  frontend:
  backend:

services:
  haproxy:
    build:
      context: .
      dockerfile: docker/haproxy/Dockerfile
    ports:
      - "80:80"
      - "8404:8404"
    networks:
      - frontend
    depends_on:
      - app1
      - app2

  app1:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    networks:
      - frontend
      - backend
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  app2:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    networks:
      - frontend
      - backend
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    build: ./docker/redis
    networks:
      - backend
    volumes:
      - redis_data:/data

volumes:
  redis_data: