apiVersion: v1
kind: Namespace
metadata:
  name: public-notes
---
# Redis Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: public-notes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Redis Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: public-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis-image
          imagePullPolicy: Never
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: public-notes
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
---
# Unified App Deployment with 2 replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: public-notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
        - name: app
          image: cloud_computing_project_2025_summer-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_REDIS_HOST
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: note-app
  namespace: public-notes
spec:
  selector:
    app: note-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: publicnotes-ingress
  namespace: public-notes
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: publicnotes.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: note-app
                port:
                  number: 8080